spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/test"
    driver-class-name: "org.postgresql.Driver"
    username: postgres
    password: 1234
  jpa:
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
    hibernate:
      ddl-auto: create-drop
  mvc:
    hiddenmethod:
      filter:
        enabled: true
#spring.mvc.hiddenmethod.filter.enabled=true
#spring.webflux.hiddenmethod.filter.enabled=true

#spring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect